"""New Migration

Revision ID: 07de3aa6ee08
Revises: 44ced196bd5f
Create Date: 2022-11-19 16:05:26.594139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07de3aa6ee08'
down_revision = '44ced196bd5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
