"""New Migration

Revision ID: 196f132a2c38
Revises: 3e51bb9007b9
Create Date: 2022-11-20 02:06:35.996751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196f132a2c38'
down_revision = '3e51bb9007b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
