"""New Migration

Revision ID: 2ba6c9974207
Revises: af601f63f054
Create Date: 2022-11-19 16:40:36.363031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba6c9974207'
down_revision = 'af601f63f054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('visit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'visit', ['visit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'visit_id')
    # ### end Alembic commands ###
