"""New Migration

Revision ID: 3a735406fdd7
Revises: d77a4233ece5
Create Date: 2022-11-19 11:07:13.599306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a735406fdd7'
down_revision = 'd77a4233ece5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
