"""New Migration

Revision ID: 3e51bb9007b9
Revises: f773aec336be
Create Date: 2022-11-20 02:04:24.246396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e51bb9007b9'
down_revision = 'f773aec336be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
