"""New Migration

Revision ID: 4a49fc455ba6
Revises: e3f2d2407f00
Create Date: 2022-11-17 14:52:38.083857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a49fc455ba6'
down_revision = 'e3f2d2407f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
