"""New Migration

Revision ID: 6547ec94f114
Revises: 2ba6c9974207
Create Date: 2022-11-20 01:55:52.010611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6547ec94f114'
down_revision = '2ba6c9974207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_visit_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'visit_id')
    op.add_column('visit', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'visit', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit', type_='foreignkey')
    op.drop_column('visit', 'order_id')
    op.add_column('order', sa.Column('visit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_visit_id_fkey', 'order', 'visit', ['visit_id'], ['id'])
    # ### end Alembic commands ###
