"""New Migration

Revision ID: 70a746d08fd1
Revises: 85ef6487e1e8
Create Date: 2022-11-20 02:35:38.688144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a746d08fd1'
down_revision = '85ef6487e1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
