"""New Migration

Revision ID: 7fa093537932
Revises: ec58e1a1fe72
Create Date: 2022-11-19 15:43:02.234949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa093537932'
down_revision = 'ec58e1a1fe72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
