"""New Migration

Revision ID: 85ef6487e1e8
Revises: fd22f2bcf689
Create Date: 2022-11-20 02:25:19.816194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ef6487e1e8'
down_revision = 'fd22f2bcf689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
