"""New Migration

Revision ID: 99098b0f84aa
Revises: d9c78eec4cf7
Create Date: 2022-11-18 14:11:37.564539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99098b0f84aa'
down_revision = 'd9c78eec4cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
