"""New Migration

Revision ID: af601f63f054
Revises: 07de3aa6ee08
Create Date: 2022-11-19 16:13:30.199024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af601f63f054'
down_revision = '07de3aa6ee08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('executor_id', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('order', sa.Column('expiration_data', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('order_executor_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'employee', ['executor_id'], ['id'])
    op.drop_column('order', 'executor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('executor', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_executor_fkey', 'order', 'employee', ['executor'], ['id'])
    op.drop_column('order', 'expiration_data')
    op.drop_column('order', 'created_at')
    op.drop_column('order', 'executor_id')
    # ### end Alembic commands ###
