"""New Migration

Revision ID: b3cc7c466a41
Revises: a46360147fa0
Create Date: 2022-11-17 14:11:20.491097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3cc7c466a41'
down_revision = 'a46360147fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('visit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'visit', ['visit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'visit_id')
    # ### end Alembic commands ###
