"""New Migration

Revision ID: b7a85401827a
Revises: 7fa093537932
Create Date: 2022-11-19 16:02:19.002844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a85401827a'
down_revision = '7fa093537932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
