"""New Migration

Revision ID: d77a4233ece5
Revises: 99098b0f84aa
Create Date: 2022-11-19 08:21:41.662832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77a4233ece5'
down_revision = '99098b0f84aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer', ['phone_number'])
    op.create_unique_constraint(None, 'employee', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_constraint(None, 'customer', type_='unique')
    # ### end Alembic commands ###
