"""New Migration

Revision ID: e3f2d2407f00
Revises: b3cc7c466a41
Create Date: 2022-11-17 14:30:07.873877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f2d2407f00'
down_revision = 'b3cc7c466a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
