"""New Migration

Revision ID: fd22f2bcf689
Revises: 196f132a2c38
Create Date: 2022-11-20 02:09:12.836904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd22f2bcf689'
down_revision = '196f132a2c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
