"""New Migration

Revision ID: fd3e4b322ff8
Revises: 3a735406fdd7
Create Date: 2022-11-19 11:10:26.017434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3e4b322ff8'
down_revision = '3a735406fdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
